

const ErrorStat = {
    NONE: { CODE: 0, NAME: "NONE", DESCRIPTION: "NO_ERROR" },
    UNKNOWN: { CODE: 1, NAME: "UNK", DESCRIPTION: "ERROR_UNKNOWN" },
    PULL: { CODE: 2, NAME: "ERROR_PULL", DESCRIPTION: "ERROR_PULLING, ERROR_UPDATE_LOCAL" },
    PUSH: { CODE: 4, NAME: "ERROR_PUSH", DESCRIPTION: "ERROR_PUSHING, ERROR_UPDATE_REMOTE" },
    EMAIL: { CODE: 8, NAME: "ERROR_EMAIL", DESCRIPTION: "ERROR_EMAIL_ADDRESS" },
    RESPONSE: { CODE: 16, NAME: "ERROR_RESPONSE", DESCRIPTION: "ERROR_SURVEY_RESPONSE" },
} as const;

export default ErrorStat;